### ISSUE TITLE
Strong handles in addition to weak ones

### ISSUE THREAD

**Issue by vadersb** [pr0g/cpp-handle-container#1]
Thank you for the great project! I wonder if it's possible within the same paradigm to have a container with an ability to request both strong and weak handles to an item.

**Comment by pr0g** [comment]
Hey @vadersb!

Thanks very much! 🙂 Really glad you've found it useful.

That's a really interesting idea... I've been thinking about it and there are quite a few options...

We might be able to make `remove` on a weak handle be a noop and have only a single strong handle per id (then this type would have to be move-only maybe?) I suppose trying to map these concepts directly back to `shared_ptr` and `weak_ptr` gets confusing 😝 As handles can actually be copied around easily they are a bit like a `weak_ptr` but as these aren't RAII types, we have to remember to call `remove`, so it's a bit different...

I'm not sure I'm afraid, I'm going to have to think about it a bit more 😄 It is a very interesting idea, if you have any ideas let me know!

Thanks again!

Tom

**Comment by vadersb** [comment]
hey @pr0g!

Thank you for sharing your thoughts! I agree that it gets very complex quickly when trying to come up with how to add strong handles! Frankly, I don't have any ideas on how to implement it decently :) Maybe it's a feature for another project and it's better to leave your current code as is, the solution is so clean and elegant.

**Comment by pr0g** [comment]
Hey @vadersb!

Not at all, 🙂 I think that's a wise idea about maybe pulling out the idea into a separate library to experiment with how it could work. The more I've been thinking about it, it almost starts feeling like handles could replicate shared/weak_ptr semantics and the container is effectively just the allocator for whatever the type is. One for another weekend perhaps 🙂

Haha you're too kind, my code is rarely very elegant 🙈 I owe a lot to the references I mention in the README, I doubt I could have come up with this on my own 😝 

Thanks!

Tom

**Comment by vadersb** [comment]
hi @pr0g! Thanks for reply, best of luck with your projects! 🙂

**Comment by pr0g** [comment]
Thanks @vadersb! You too! I'll keep you posted on future developments 😁
